<?php

use Illuminate\Support\Facades\Auth;

if (!function_exists('getUniqueTrapId')) {
    function getUniqueTrapId() {
        $found = false;
        while(!$found) {
            $mouri_words = [
                'Awa',
                'Hui',
                'Iti',
                'Kai',
                'Moa',
                'Nui',
                'Wai',
                'Roa',
                'One',
                'Pae',
                'Tai',
                'Ihu',
                'Tui',
                'Kea',
                'Haka',
                'Hapu',
                'Kiwi',
                'Koha',
                'Mahi',
                'Mana',
                'Motu',
                'Puku',
                'Waka',
                'Tapu',
                'Papa',
                'Poto',
                'Puke',
                'Niho',
                'Poho',
                'Raho',
                'Toto',
                'Turi',
                'Hihi',
                'Huia',
                'Kaka',
                'Tara',
                'Ruru',
                'Weka',
                'Whio',
                'Tane',
                'Rimu',
                'Rata',
                'Puha',
                'Miro',
                'Tawa',
                'Tutu',
                'Aroha',
                'Hangi',
                'Kauri',
                'Moana',
                'Arero',
                'Kauae',
                'Ringa',
                'Upoko',
                'Totoa',
                'Kuaka',
                'Torea',
                'Poaka',
                'Tieke',
                'Mauri',
                'Aruhe',
                'Nikau',
                'Matai',
                'Wheki',
                'Ponga',
                'Hinau',
                'Raupo',
                'Manawa',
                'Kakapo',
                'Kereru',
                'Kotuku',
                'Takapu',
                'Matata',
                'Matuku',
                'Karoro',
                'Piopio',
                'Kokako',
                'Koreke',
                'Kawau',
                'Kotare',
                'Parera',
                'Pukeko',
                'Hokioi',
                'Hoiho',
                'Korora',
                'Takahe',
                'Totara',
                'Manuka',
                'Kanuka',
                'Kowhai',
                'Tawhai',
                'Mamaku',
                'Katote',
                'Titoki',
            ];
            $id = str_pad(rand(0, pow(10, 4)-1), 4, '0', STR_PAD_LEFT);
            $word = $mouri_words[array_rand($mouri_words, 1)];
            $candidate = $word . '-' . $id;
            if(! \App\Models\Trap::where('qr_id', $candidate)->exists()) {
                return $candidate;
            }
        }
    }
}
